name: Create Infra
on:
  workflow_dispatch:

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_KEY: ${{ secrets.ssh-key-terraform }}
  #AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  Create-Infrastructure:
    name: Create Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.5.0"
      - name: Step to Checkout the code 
        uses: actions/checkout@v4
      - name: Prepare HTML
        run : |
          sed -i "s/PLACEHOLDER_USER/${{ github.GITHUB_USER }}-${{ github.actor }}/g" ../project-code/%html%
          sed -i "s/PLACEHOLDER_BRANCH/${{ github.ref_name }}/g" ../project-code/%html%
      - name: Setup ssh
        run: echo "$SSH_KEY" > id_rsa
      - name: Perform terraform Init 
        run: terraform init -backend-config="bucket=bucket=malti-terraform-s3-bucket" -backend-config="key=statefile/${{ github.ref_name }}/terraform.tfstate" -backend-config="region=eu-central-1"
      - name: Perform terraform plan
        run: terraform plan -var "branch_name=${{ github.ref_name }}" 
      - name: Perform terraform apply
        run: terraform apply -var "branch_name=${{ github.ref_name }}" --auto-approve



